stages:
  - Build
  - Test

cache:
  key: ${CI_PIPELINE_ID}
  paths:
    - build/windows
    - build/linux
    - build/android
    - output

Windows:
  stage: Build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    paths:
      - build/windows
    expire_in: 1d
  tags:
    - gpu
  script:
    - cmake -G"Visual Studio 15 2017 Win64" -H. -Bbuild/windows -DVKB_BUILD_TESTS:BOOL=ON -DVKB_BUILD_SAMPLES:BOOL=ON
    - cmake --build build/windows --target vulkan_samples --config Release

SystemTest:
  stage: Test
  variables:
   GIT_SUBMODULE_STRATEGY: recursive
  artifacts:
    paths:
      - tests/system_test/artifacts
    expire_in: 1d
    when: on_failure
  dependencies:
   - Windows
  tags:
   - gpu
  script:
   - cd tests/system_test
   - python system_test.py -Bbuild/windows -CRelease -D -P